[alias]
build-arm = "build --target=thumbv8m.main-none-eabihf"
run-arm = "run --target=thumbv8m.main-none-eabihf"


[build]
target = "thumbv8m.main-none-eabihf"

[target.thumbv8m.main-none-eabihf]
rustflags = [
#  "-L", "/home/esarver/Projects/RP2350-Embassy-Playground/_00-blinky/target/thumbv8m.main-none-eabihf/debug/build/cortex-m-rt-738c3ae145c9fdc1/out",
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "target-cpu=cortex-m33",
  ]
runner = "probe-rs run --chip rp235x"
#runner = "picotool load -u -v -x -t elf"


[env]
DEFMT_LOG = "info"
